-- =============================================================================
-- LoadStar Freight Intelligence
-- 01: Raw Tables DDL
-- Creates all source tables in the RAW schema
-- =============================================================================

USE DATABASE FREIGHT_DEMO;
USE SCHEMA RAW;

-- Broker profiles (200 rows)
CREATE OR REPLACE TABLE BROKER_PROFILES (
    BROKER_ID NUMBER(18,0),
    MC_NUMBER VARCHAR(16777216),
    BROKER_NAME VARCHAR(16777216),
    CREDIT_SCORE NUMBER(3,0),
    FACTORING_RATE_PCT NUMBER(38,0),
    FACTORING_TYPE VARCHAR(12),
    HQ_STATE VARIANT,
    RELATIONSHIP_START DATE,
    TOTAL_FACTORED_VOLUME NUMBER(38,0),
    DOUBLE_BROKER_FLAG BOOLEAN,
    DISPUTE_COUNT NUMBER(2,0),
    STATUS VARCHAR(9)
);

-- Carrier profiles (500 rows)
-- Note: DRIVER_SSN and BANK_ACCOUNT_NUMBER will have masking policies applied in 05_create_governance.sql
CREATE OR REPLACE TABLE CARRIER_PROFILES (
    CARRIER_ID NUMBER(18,0),
    MC_NUMBER VARCHAR(16777216),
    CARRIER_NAME VARCHAR(16777216),
    EQUIPMENT_TYPE VARIANT,
    FLEET_SIZE NUMBER(2,0),
    HOME_STATE VARIANT,
    HOME_CITY VARIANT,
    HOME_LONGITUDE NUMBER(38,0),
    HOME_LATITUDE NUMBER(38,0),
    ONBOARDED_DATE DATE,
    STATUS VARCHAR(8),
    DRIVER_SSN VARCHAR(16777216),
    BANK_ACCOUNT_NUMBER VARCHAR(16777216)
);

-- Invoice transactions (10,000 rows)
CREATE OR REPLACE TABLE INVOICE_TRANSACTIONS (
    INVOICE_ID VARCHAR(16777216),
    BROKER_ID NUMBER(3,0),
    CARRIER_ID NUMBER(3,0),
    INVOICE_AMOUNT NUMBER(38,0),
    FACTORING_FEE_PCT NUMBER(38,0),
    INVOICE_DATE DATE,
    FACTORED_DATE DATE,
    PAYMENT_RECEIVED_DATE DATE,
    ORIGIN_CITY VARIANT,
    DESTINATION_CITY VARIANT,
    MILES NUMBER(4,0),
    STATUS VARCHAR(20),
    EQUIPMENT_TYPE VARIANT,
    FUNDING_METHOD VARIANT
);

-- Load postings (5,000 rows)
CREATE OR REPLACE TABLE LOAD_POSTINGS (
    LOAD_ID VARCHAR(16777216),
    BROKER_ID NUMBER(3,0),
    ORIGIN_CITY VARIANT,
    ORIGIN_STATE VARIANT,
    ORIGIN_LONGITUDE NUMBER(38,0),
    ORIGIN_LATITUDE NUMBER(38,0),
    DESTINATION_CITY VARIANT,
    DESTINATION_STATE VARIANT,
    MILES NUMBER(4,0),
    RATE_PER_MILE NUMBER(38,0),
    TOTAL_RATE NUMBER(38,0),
    EQUIPMENT_REQUIRED VARIANT,
    WEIGHT_LBS NUMBER(5,0),
    PICKUP_DATE TIMESTAMP_LTZ(9),
    DELIVERY_DATE TIMESTAMP_LTZ(9),
    STATUS VARCHAR(10),
    POSTED_AT TIMESTAMP_LTZ(9),
    ORIGIN_STATE_CODE VARCHAR(16777216)
);

-- Texas weather data (from Snowflake Marketplace)
CREATE OR REPLACE TABLE TEXAS_WEATHER (
    CITY_NAME VARCHAR(65),
    POSTAL_CODE VARCHAR(20),
    DATE_VALID_STD DATE,
    AVG_TEMP_F NUMBER(38,1),
    MAX_WIND_MPH NUMBER(38,1),
    PRECIPITATION_IN NUMBER(38,2),
    SNOWFALL_IN NUMBER(38,2),
    CLOUD_COVER_PCT NUMBER(38,0),
    WEATHER_RISK_LEVEL VARCHAR(6)
);

-- JSON staging table for streaming simulation
CREATE OR REPLACE TABLE INVOICE_TRANSACTIONS_JSON (
    RAW_DATA VARIANT,
    INGESTED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
