-- =============================================================================
-- LoadStar Freight Intelligence
-- 99: Teardown
-- Cleanly removes all demo objects in reverse dependency order.
-- Run this to completely reset the environment.
-- =============================================================================

-- Stop streaming task first
ALTER TASK IF EXISTS FREIGHT_DEMO.RAW.SIMULATE_STREAMING_INGESTION SUSPEND;

-- Agent (depends on semantic view)
DROP AGENT IF EXISTS FREIGHT_DEMO.ANALYTICS.BROKER_AGENT;

-- Semantic View (depends on dynamic table)
DROP SEMANTIC VIEW IF EXISTS FREIGHT_DEMO.ANALYTICS.BROKER_360_SV;

-- Dynamic Table
DROP DYNAMIC TABLE IF EXISTS FREIGHT_DEMO.ANALYTICS.BROKER_360;

-- Git Repository
DROP GIT REPOSITORY IF EXISTS FREIGHT_DEMO.ANALYTICS.LOADSTAR_REPO;

-- UDF and Stored Procedure
DROP FUNCTION IF EXISTS FREIGHT_DEMO.ML.GET_RECOMMENDATION_SCORE(NUMBER, NUMBER);
DROP PROCEDURE IF EXISTS FREIGHT_DEMO.ML.POPULATE_RECOMMENDATIONS();
DROP TABLE IF EXISTS FREIGHT_DEMO.ML.CARRIERMATCH_RECOMMENDATIONS;

-- Notebook (if exists)
DROP NOTEBOOK IF EXISTS FREIGHT_DEMO.ANALYTICS.FREIGHT_360_DEMO;

-- Model
DROP MODEL IF EXISTS FREIGHT_DEMO.ML.BROKER_RISK_NET;

-- Streaming pipeline
DROP TASK IF EXISTS FREIGHT_DEMO.RAW.SIMULATE_STREAMING_INGESTION;
DROP STREAM IF EXISTS FREIGHT_DEMO.RAW.INVOICE_JSON_STREAM;
DROP VIEW IF EXISTS FREIGHT_DEMO.RAW.INVOICE_TRANSACTIONS_FLATTENED;

-- Remove masking policies from columns first (required before dropping policies)
ALTER TABLE FREIGHT_DEMO.RAW.CARRIER_PROFILES MODIFY COLUMN DRIVER_SSN UNSET MASKING POLICY;
ALTER TABLE FREIGHT_DEMO.RAW.CARRIER_PROFILES MODIFY COLUMN BANK_ACCOUNT_NUMBER UNSET MASKING POLICY;
ALTER TABLE FREIGHT_DEMO.RAW.CARRIER_PROFILES MODIFY COLUMN DRIVER_SSN UNSET TAG FREIGHT_DEMO.RAW.PII_TYPE;
ALTER TABLE FREIGHT_DEMO.RAW.CARRIER_PROFILES MODIFY COLUMN BANK_ACCOUNT_NUMBER UNSET TAG FREIGHT_DEMO.RAW.PII_TYPE;

-- Governance objects
DROP MASKING POLICY IF EXISTS FREIGHT_DEMO.RAW.SSN_MASK;
DROP MASKING POLICY IF EXISTS FREIGHT_DEMO.RAW.BANK_ACCOUNT_MASK;
DROP TAG IF EXISTS FREIGHT_DEMO.RAW.PII_TYPE;

-- Tables
DROP TABLE IF EXISTS FREIGHT_DEMO.RAW.INVOICE_TRANSACTIONS_JSON;
DROP TABLE IF EXISTS FREIGHT_DEMO.RAW.TEXAS_WEATHER;
DROP TABLE IF EXISTS FREIGHT_DEMO.RAW.LOAD_POSTINGS;
DROP TABLE IF EXISTS FREIGHT_DEMO.RAW.INVOICE_TRANSACTIONS;
DROP TABLE IF EXISTS FREIGHT_DEMO.RAW.CARRIER_PROFILES;
DROP TABLE IF EXISTS FREIGHT_DEMO.RAW.BROKER_PROFILES;

-- DS Sandbox clones
DROP TABLE IF EXISTS FREIGHT_DEMO.DS_SANDBOX.BROKER_PROFILES;
DROP TABLE IF EXISTS FREIGHT_DEMO.DS_SANDBOX.CARRIER_PROFILES;
DROP TABLE IF EXISTS FREIGHT_DEMO.DS_SANDBOX.INVOICE_TRANSACTIONS;
DROP TABLE IF EXISTS FREIGHT_DEMO.DS_SANDBOX.LOAD_POSTINGS;
DROP TABLE IF EXISTS FREIGHT_DEMO.DS_SANDBOX.TEXAS_WEATHER;

-- API Integration
DROP API INTEGRATION IF EXISTS GIT_API_INTEGRATION;

-- Roles
DROP ROLE IF EXISTS FREIGHT_ANALYST;
DROP ROLE IF EXISTS FREIGHT_DATA_SCIENTIST;
DROP ROLE IF EXISTS FREIGHT_OPS;

-- Compute Pool
DROP COMPUTE POOL IF EXISTS GPU_POOL;

-- Warehouses
DROP WAREHOUSE IF EXISTS DS_SANDBOX_WH;
DROP WAREHOUSE IF EXISTS ANALYTICS_WH;

-- Schemas (in dependency order)
DROP SCHEMA IF EXISTS FREIGHT_DEMO.DS_SANDBOX;
DROP SCHEMA IF EXISTS FREIGHT_DEMO.ML;
DROP SCHEMA IF EXISTS FREIGHT_DEMO.ANALYTICS;
DROP SCHEMA IF EXISTS FREIGHT_DEMO.STAGING;
DROP SCHEMA IF EXISTS FREIGHT_DEMO.RAW;

-- Database (final)
DROP DATABASE IF EXISTS FREIGHT_DEMO;
